### ISSUE TITLE
Supplying Username and Password?

### ISSUE THREAD

**Issue by Adamcina** [Weatherlights/Intune-Network-Drive-Mapping-Tool#1]
Hello,

I was wondering if it's possible somehow to supply username and password credentials so I could map network drives to users' devices?
They are unable to connect to network drives by using their credentials because network drives require some other username&password credentials.

Thanks in advance!

**Comment by Weatherlights** [comment]
Hey technically hat could be implemented... but currently this feature was left out intentionally since the authentication should rely on the build in mechanism (so for example Windows Hello for Business). May I ask why this is not an option? Then I can better understand for whom could this be interesting.

**Comment by Adamcina** [comment]
Thanks for the answer!
This is the situation that we have in our company - we have a file server (Windows Server 2012R2) that has on itself several local users who have different permissions or precisely - they have access to different folders. For example, User1 has access to Folder1 only, User2 has access to Folder2 only, etc.
Now, we want to map different network drives to different Microsoft365 users, so they could have access to the drive (folder) they need. For example, employee1@contoso.com needs access to Folder2, so we would need to supply User2 credentials in order to map the network drive to Employee1's device.

I hope that I have explained this well enough

**Comment by Weatherlights** [comment]
I can look into the implementation of this :). However I strongly recommend you to use a SmartCard/Certificate based mechanism.

**Comment by Weatherlights** [comment]
I added the Feature for version 1.1.0.0 and updated the documentation. The update will be released within the next 3-4 hours.

**Comment by Adamcina** [comment]
Thank you very much!

Cheers!
