### ISSUE TITLE
Drives not mapping but logs seem ok

### ISSUE THREAD

**Issue by bpmarine** [Weatherlights/Intune-Network-Drive-Mapping-Tool#2]
Thanks for your handy tool, I'm hoping I can make it work!

My logs look ok, but the drives are not mapping for me:

`<![LOG[Will now connect O to \\10.11.12.7\MAL]LOG]!><time="16:54:46.980-000" date="03-04-2022" component="DriveSettings" context="" type="1" thread="1" file="">
<![LOG[Will now connect P to \\10.11.12.7\Projects]LOG]!><time="16:54:46.981-000" date="03-04-2022" component="DriveSettings" context="" type="1" thread="1" file="">
<![LOG[Will now go to sleep.]LOG]!><time="16:54:56.997-000" date="03-04-2022" component="NetworkDriveMapping" context="" type="1" thread="1" file="">`

I have checked the network paths directly in File Explorer and I can browse them without issues.

My ADMX template ingestion and the drive configs are on different policies. I'm using Enabled, Refresh Interval and Map Persistent with the /"enabled/"/ string, and only have these two drives in the Network Share Mappings settings. The logs suggest that everything is being read correctly, but it's not showing drives after many reboots and syncs via Company Portal.

Any suggestions would be appreciated! BTW, Windows 21H2

**Comment by Weatherlights** [comment]
Do you connect them using shared credentials?

Am 04.03.2022 um 18:05 schrieb bpmarine ***@***.***>:

﻿

Thanks for your handy tool, I'm hoping I can make it work!

My logs look ok, but the drives are not mapping for me:

<![LOG[Will now connect O to \\10.11.12.7\MAL]LOG]!><time="16:54:46.980-000" date="03-04-2022" component="DriveSettings" context="" type="1" thread="1" file=""> <![LOG[Will now connect P to \\10.11.12.7\Projects]LOG]!><time="16:54:46.981-000" date="03-04-2022" component="DriveSettings" context="" type="1" thread="1" file=""> <![LOG[Will now go to sleep.]LOG]!><time="16:54:56.997-000" date="03-04-2022" component="NetworkDriveMapping" context="" type="1" thread="1" file="">

I have checked the network paths directly in File Explorer and I can browse them without issues.

My ADMX template ingestion and the drive configs are on different policies. I'm using Enabled, Refresh Interval and Map Persistent with the string, and only have these two drives in the Network Share Mappings settings. The logs suggest that everything is being ready correctly, but it's not showing drives after many reboots and syncs via Company Portal.

Any suggestions would be appreciated! BTW, Windows 21H2

**Comment by Weatherlights** [comment]
Hello

I created a new release that mainly improves logging. Please update and check the logs again and see if there are some additional informations. Please keep me updated :).

Best
Hauke

**Comment by bpmarine** [comment]
Hi Hauke

Thanks very much, I will test later today and let you know.

Best regards
Brandon

**Comment by bpmarine** [comment]
Good morning Hauke

Here is the useful part of the log, hopefully this error code provides more insight:

<![LOG[Drive mapping failed with code: 1202]LOG]!><time="09:39:14.960-000" date="03-10-2022" component="DriveSettings" context="" type="2" thread="1" file="">

Best regards
Brandon

From: Brandon Mason
Sent: 09 March 2022 09:59
To: Weatherlights/Intune-Network-Drive-Mapping-Tool ***@***.***>; Weatherlights/Intune-Network-Drive-Mapping-Tool ***@***.***>
Cc: Author ***@***.***>
Subject: RE: [Weatherlights/Intune-Network-Drive-Mapping-Tool] Drives not mapping but logs seem ok (Issue #2)

Hi Hauke

Thanks very much, I will test later today and let you know.

Best regards
Brandon

**Comment by Weatherlights** [comment]
Hey

did you use MapPersistent?

Best
Hauke

**Comment by bpmarine** [comment]
Morning

Yes, Map Persistent > <enabled/>.

I just saw that the custom policy to map the drives has not successfully applied to my assigned devices. I have the admx ingestion as a separate policy from the four conjuration settings: Enabled, Refresh Interval, Map Persistent and Network Share Mappings. These four have not applied according to Endpoint.

Perhaps I have a syntax error on Network Share Mappings:

<enabled/><data id="NetworkDriveMappingsList" value="1&#xF000;O;\\10.11.12.7\mal&#xF000;2&#xF000;P;\\10.11.12.7\Projects"/>

I can't seem to find any error log on Endpoint to see why it's failing to apply successfully as yet.

Brandon

**Comment by Weatherlights** [comment]
Hey

you can check the the following registry key to see if your configuration is applied successfully: HKEY_CURRENT_USER\Software\Policies\weatherlights.com

Intune sometimes falsely reports that a setting is not applied (this has something to do with the "LineBreak" Formatting in the ADMX Template).

However: The error 1202 translates to ERROR_DEVICE_ALREADY_REMEMBERED (The local device name has a remembered connection to another network resource). For the start I would recommend you to disable MapPersistent (as a matter of fact you do not need it at all it is in there for legacy reasons). Afterwards I would recommend you to remove all existing network connections on your machine (or use a blank machine).

Also: Is there something else that maps drives on your machine (A script or anything) that could be in conflict?

Best
Hauke

**Comment by Weatherlights** [comment]
Also check this guide here that has something nice ideas how to troubleshoot:
https://appuals.com/how-to-fix-the-local-device-name-is-already-in-use-error-on-windows/

**Comment by bpmarine** [comment]
Thank you. The registry key is present. I have removed Map Persistent.

I have previously tried to map these drives using powershell scripts and https://www.anoopcnair.com/managing-network-drive-mappings-with-intune/ this guide.

There must be something left, though I have removed all Task Scheduler and registry keys I can find that seem relevant. Must have missed something.

I will try it on a clean machine when I get a chance.

**Comment by bpmarine** [comment]
Success!

I checked HKEY_CURRENT_USER\Network for old drive mappings and had O and P listed. I deleted the registry keys, disabled and re-enabled the network, drives immediately mapped!

Thanks for your help, glad to report it's working. I really like the feature that checks multiple times for a connection and listens for change of network state. Really useful for mapping across my wireguard/netmaker setup.

Best regards
Brandon

From: Brandon Mason
Sent: 10 March 2022 10:21
To: Weatherlights/Intune-Network-Drive-Mapping-Tool ***@***.***>; Weatherlights/Intune-Network-Drive-Mapping-Tool ***@***.***>
Cc: Author ***@***.***>
Subject: RE: [Weatherlights/Intune-Network-Drive-Mapping-Tool] Drives not mapping but logs seem ok (Issue #2)

Thank you. The registry key is present. I have removed Map Persistent.

I have previously tried to map these drives using powershell scripts and https://www.anoopcnair.com/managing-network-drive-mappings-with-intune/ this guide.

There must be something left, though I have removed all Task Scheduler and registry keys I can find that seem relevant. Must have missed something.

I will try it on a clean machine when I get a chance.

**Comment by Weatherlights** [comment]
Ahhh nice that we got this one resolved :).

Well thank you very much for the feedback. If you like I really appreciate a nice comment in the Microsoft Store ;).

Thank you again and have a great day
Hauke

**Comment by bpmarine** [comment]
Thanks Hauke

I certainly will do that. You too.

Best regards
Brandon
