### ISSUE TITLE
Issue with persistent value

### ISSUE THREAD

**Issue by SunnyCarsGitHub** [Weatherlights/Intune-Network-Drive-Mapping-Tool#8]
We have an issue with the persistence option.
When we configure the OMA-URI like the wiki, then we got an error during the deployment over intune:

./User/Vendor/MSFT/Policy/Config/weatherlightscom~Policy~IntuneNetworkShareMapper~Configuration/MapPersistent

When we change the OMA-URI to this below we can deploy the configuration, but the network drives are still not persistent mapped.

./User/Vendor/MSFT/Policy/Config/weatherlights~Policy~IntuneNetworkShareMapper~Configuration/MapPersistent

We can see in the registry the value 1 for the DWORD "MapPersistent" under Computer\HKEY_CURRENT_USER\Software\Policies\weatherlights.com\NetworkDriveMapping.

Could someone help me out here?
Thank you in advance!

**Comment by Weatherlights** [comment]
I recommend you not use the value... the tool is desigend to connect when connection is possible so the persistence does not much on top. The map presistent was implemented very early and is just a flag for Windows and windows does not handle it that well.
