### ISSUE TITLE
Error 67 in Log File

### ISSUE THREAD

**Issue by SannyBoyy** [Weatherlights/Intune-Network-Drive-Mapping-Tool#9]
Hey, i was trying to implement this to for the network drive mapping at the company i'm working for. 

The deploy works but i was wondering, why there was still no network drive. I looked up the log file and it is failed because of Error 67. Has somebody else experience with this behavior?

**Comment by Weatherlights** [comment]
This refers to the following error: System error 67 has occurred. The network name cannot be found
https://learn.microsoft.com/en-us/troubleshoot/windows-server/networking/system-error-67-network-name-cannot-be-found

The drive can not be connected due to a connection error (server not reachable, dns name not resolved). What happens if you try the connection manually on the device?

**Comment by SannyBoyy** [comment]
I can reach the drive with using net use and it is also reachable via searching normaly in the windows explorer. 

I was also reading this article before asking. I could try searching updates for the network adapter but disabling NAT seems a little bit risky.

**Comment by Weatherlights** [comment]
Nahhh yea that will not help that much... May I see your configuration (just replace your company name with something else).

**Comment by Weatherlights** [comment]
Oh and the log maybe too :)

**Comment by SannyBoyy** [comment]
[Execution.log](https://github.com/user-attachments/files/15984957/Execution.log)

This is the log, do you just want the NetworkDriveMapping Configuration or also the other OMA URI?

**Comment by Weatherlights** [comment]
The Intune profile would do it
________________________________
Von: SannyBoyy ***@***.***>
Gesendet: Mittwoch, 26. Juni 2024 10:39
An: Weatherlights/Intune-Network-Drive-Mapping-Tool ***@***.***>
Cc: Hauke Götze ***@***.***>; Comment ***@***.***>
Betreff: Re: [Weatherlights/Intune-Network-Drive-Mapping-Tool] Error 67 in Log File (Issue #9)


Execution.log<https://github.com/user-attachments/files/15984957/Execution.log>

This is the log, do you just want the NetworkDriveMapping Configuration or also the other OMA URI?

**Comment by SannyBoyy** [comment]
[exportieren (1).csv](https://github.com/user-attachments/files/15985943/exportieren.1.csv)

I guess this is what you mean

**Comment by Weatherlights** [comment]
Check the configuration 🙂. I; \\firedos.local\Daten there is an empty space between the ; and \\... Is this also showing in the registry. May I have an export from that aswell 🙂

**Comment by SannyBoyy** [comment]
I guess you were right. I just wiped the PC again and deleted the space in the configuration. Many thanks for your quick help and schöne Grüße nach Schleswig-Holstein :)
